# ENVI Ledger constants

CURRENCY_NAME = "Nexus Credits"
CURRENCY_SYMBOL = "₦C"

STARTING_BALANCE = 0

DAILY_AMOUNT = 500
DAILY_COOLDOWN_SECONDS = 24 * 60 * 60

WORK_MIN_AMOUNT = 150
WORK_MAX_AMOUNT = 500
WORK_COOLDOWN_SECONDS = 4 * 60 * 60

LEADERBOARD_LIMIT = 10

# ENVI green from the Exordium Nexus visual system
ENVI_GREEN = 0x40EF5B

TRANSACTION_DAILY = "DAILY_CLAIM"
TRANSACTION_WORK = "WORK_PAYOUT"
TRANSACTION_TRANSFER_SENT = "USER_TRANSFER_SENT"
TRANSACTION_TRANSFER_RECEIVED = "USER_TRANSFER_RECEIVED"
TRANSACTION_SHOP_PURCHASE = "SHOP_PURCHASE"
TRANSACTION_ADMIN_ADD = "ADMIN_ADD"
TRANSACTION_ADMIN_REMOVE = "ADMIN_REMOVE"
TRANSACTION_ADMIN_SET = "ADMIN_SET"
TRANSACTION_ADMIN_RESET = "ADMIN_RESET"


# -----------------------------
# V1.5 Shop Metadata
# -----------------------------

DEFAULT_SHOP_CATEGORY = "General"
DEFAULT_ITEM_RARITY = "Common"
DEFAULT_ITEM_USABLE = False
DEFAULT_ITEM_CONSUMABLE = False

SHOP_CATEGORIES = (
    "General",
    "Food & Drink",
    "Luxury",
    "Transit",
    "Access Passes",
    "Obsession Items",
    "Eclipse Items",
    "Foxy Delights Items",
    "Black Badge / Civic",
    "Collectibles",
    "Event Items",
)

ITEM_RARITIES = (
    "Common",
    "Uncommon",
    "Rare",
    "Luxury",
    "Restricted",
    "Exordium-Class",
)

# -----------------------------
# V2 Organization Foundation
# -----------------------------

ORGANIZATION_TYPE_BUSINESS = "BUSINESS"
ORGANIZATION_TYPE_INSTITUTION = "INSTITUTION"
ORGANIZATION_TYPE_GOVERNMENT = "GOVERNMENT"
ORGANIZATION_TYPE_FACTION = "FACTION"

ORGANIZATION_TYPES = (
    ORGANIZATION_TYPE_BUSINESS,
    ORGANIZATION_TYPE_INSTITUTION,
    ORGANIZATION_TYPE_GOVERNMENT,
    ORGANIZATION_TYPE_FACTION,
)

ORGANIZATION_NAME_MAX_LENGTH = 100
ORGANIZATION_DESCRIPTION_MAX_LENGTH = 1000

ORGANIZATION_TRANSACTION_TYPE_MAX_LENGTH = 64
ORGANIZATION_TRANSACTION_REASON_MAX_LENGTH = 500
ORGANIZATION_REFERENCE_ID_MAX_LENGTH = 100

ORGANIZATION_AUTOCOMPLETE_LIMIT = 25