# ENVI Ledger constants

CURRENCY_NAME = "Nexus Credits"
CURRENCY_SYMBOL = "₦C"

STARTING_BALANCE = 0

DAILY_AMOUNT = 500
DAILY_COOLDOWN_SECONDS = 24 * 60 * 60

WORK_MIN_AMOUNT = 150
WORK_MAX_AMOUNT = 500
WORK_COOLDOWN_SECONDS = 4 * 60 * 60

LEADERBOARD_LIMIT = 10

# ENVI green from the Exordium Nexus visual system
ENVI_GREEN = 0x40EF5B

TRANSACTION_DAILY = "DAILY_CLAIM"
TRANSACTION_WORK = "WORK_PAYOUT"
TRANSACTION_TRANSFER_SENT = "USER_TRANSFER_SENT"
TRANSACTION_TRANSFER_RECEIVED = "USER_TRANSFER_RECEIVED"
TRANSACTION_SHOP_PURCHASE = "SHOP_PURCHASE"
TRANSACTION_ADMIN_ADD = "ADMIN_ADD"
TRANSACTION_ADMIN_REMOVE = "ADMIN_REMOVE"
TRANSACTION_ADMIN_SET = "ADMIN_SET"
TRANSACTION_ADMIN_RESET = "ADMIN_RESET"


# -----------------------------
# V1.5 Shop Metadata
# -----------------------------

DEFAULT_SHOP_CATEGORY = "General"
DEFAULT_ITEM_RARITY = "Common"
DEFAULT_ITEM_USABLE = False
DEFAULT_ITEM_CONSUMABLE = False

SHOP_CATEGORIES = (
    "General",
    "Food & Drink",
    "Luxury",
    "Transit",
    "Access Passes",
    "Obsession Items",
    "Eclipse Items",
    "Foxy Delights Items",
    "Black Badge / Civic",
    "Collectibles",
    "Event Items",
)

ITEM_RARITIES = (
    "Common",
    "Uncommon",
    "Rare",
    "Luxury",
    "Restricted",
    "Exordium-Class",
)

SHOP_SYSTEM_SELLER_VALUE = "__SYSTEM__"

SHOP_SYSTEM_SELLER_LABEL = (
    "ENVI Commercial Exchange — System-Owned"
)

# -----------------------------
# V2 Organization Foundation
# -----------------------------

ORGANIZATION_TYPE_BUSINESS = "BUSINESS"
ORGANIZATION_TYPE_INSTITUTION = "INSTITUTION"
ORGANIZATION_TYPE_GOVERNMENT = "GOVERNMENT"
ORGANIZATION_TYPE_FACTION = "FACTION"

ORGANIZATION_TYPES = (
    ORGANIZATION_TYPE_BUSINESS,
    ORGANIZATION_TYPE_INSTITUTION,
    ORGANIZATION_TYPE_GOVERNMENT,
    ORGANIZATION_TYPE_FACTION,
)

ORGANIZATION_NAME_MAX_LENGTH = 100
ORGANIZATION_DESCRIPTION_MAX_LENGTH = 1000

ORGANIZATION_TRANSACTION_TYPE_MAX_LENGTH = 64
ORGANIZATION_TRANSACTION_REASON_MAX_LENGTH = 500
ORGANIZATION_REFERENCE_ID_MAX_LENGTH = 100

ORGANIZATION_AUTOCOMPLETE_LIMIT = 25

# -----------------------------
# V2 Organization Membership
# -----------------------------

ORGANIZATION_ROLE_OWNER = "OWNER"
ORGANIZATION_ROLE_MANAGER = "MANAGER"
ORGANIZATION_ROLE_MEMBER = "MEMBER"

ORGANIZATION_ROLES = (
    ORGANIZATION_ROLE_OWNER,
    ORGANIZATION_ROLE_MANAGER,
    ORGANIZATION_ROLE_MEMBER,
)

ORGANIZATION_PERMISSION_VIEW_INFO = "VIEW_INFO"
ORGANIZATION_PERMISSION_VIEW_MEMBERS = "VIEW_MEMBERS"
ORGANIZATION_PERMISSION_VIEW_BALANCE = "VIEW_BALANCE"
ORGANIZATION_PERMISSION_VIEW_LEDGER = "VIEW_LEDGER"
ORGANIZATION_PERMISSION_DEPOSIT = "DEPOSIT"
ORGANIZATION_PERMISSION_PAY_USER = "PAY_USER"
ORGANIZATION_PERMISSION_PAY_ORGANIZATION = (
    "PAY_ORGANIZATION"
)
ORGANIZATION_PERMISSION_MANAGE_MEMBERS = (
    "MANAGE_MEMBERS"
)
ORGANIZATION_PERMISSION_MANAGE_ROLES = (
    "MANAGE_ROLES"
)
ORGANIZATION_PERMISSION_REMOVE_MEMBERS = (
    "REMOVE_MEMBERS"
)

ORGANIZATION_PERMISSIONS = (
    ORGANIZATION_PERMISSION_VIEW_INFO,
    ORGANIZATION_PERMISSION_VIEW_MEMBERS,
    ORGANIZATION_PERMISSION_VIEW_BALANCE,
    ORGANIZATION_PERMISSION_VIEW_LEDGER,
    ORGANIZATION_PERMISSION_DEPOSIT,
    ORGANIZATION_PERMISSION_PAY_USER,
    ORGANIZATION_PERMISSION_PAY_ORGANIZATION,
    ORGANIZATION_PERMISSION_MANAGE_MEMBERS,
    ORGANIZATION_PERMISSION_MANAGE_ROLES,
    ORGANIZATION_PERMISSION_REMOVE_MEMBERS,
)

ORGANIZATION_ROLE_PERMISSIONS = {
    ORGANIZATION_ROLE_OWNER: frozenset(
        ORGANIZATION_PERMISSIONS
    ),
    ORGANIZATION_ROLE_MANAGER: frozenset(
        (
            ORGANIZATION_PERMISSION_VIEW_INFO,
            ORGANIZATION_PERMISSION_VIEW_MEMBERS,
            ORGANIZATION_PERMISSION_VIEW_BALANCE,
            ORGANIZATION_PERMISSION_VIEW_LEDGER,
            ORGANIZATION_PERMISSION_DEPOSIT,
            ORGANIZATION_PERMISSION_PAY_USER,
            ORGANIZATION_PERMISSION_PAY_ORGANIZATION,
        )
    ),
    ORGANIZATION_ROLE_MEMBER: frozenset(
        (
            ORGANIZATION_PERMISSION_VIEW_INFO,
            ORGANIZATION_PERMISSION_VIEW_MEMBERS,
        )
    ),
}

# -----------------------------
# V2 Organization Finance
# -----------------------------

TRANSACTION_ORGANIZATION_DEPOSIT = (
    "ORGANIZATION_DEPOSIT"
)

ORGANIZATION_TRANSACTION_MEMBER_DEPOSIT = (
    "MEMBER_DEPOSIT"
)

ORGANIZATION_DEPOSIT_REFERENCE_PREFIX = (
    "ORGDEP"
)

TRANSACTION_ORGANIZATION_USER_PAYMENT_RECEIVED = (
    "ORGANIZATION_USER_PAYMENT_RECEIVED"
)

ORGANIZATION_TRANSACTION_USER_PAYMENT = (
    "USER_PAYMENT"
)

ORGANIZATION_USER_PAYMENT_REFERENCE_PREFIX = (
    "ORGPAYUSR"
)

ORGANIZATION_TRANSACTION_PAYMENT_SENT = (
    "ORGANIZATION_PAYMENT_SENT"
)

ORGANIZATION_TRANSACTION_PAYMENT_RECEIVED = (
    "ORGANIZATION_PAYMENT_RECEIVED"
)

ORGANIZATION_PAYMENT_REFERENCE_PREFIX = (
    "ORGPAYORG"
)

ORGANIZATION_TRANSACTION_ADMIN_REVENUE = (
    "ADMIN_REVENUE"
)

ORGANIZATION_TRANSACTION_ADMIN_BALANCE_SET = (
    "ADMIN_BALANCE_SET"
)

ORGANIZATION_REVENUE_REFERENCE_PREFIX = (
    "ORGREV"
)

ORGANIZATION_BALANCE_SET_REFERENCE_PREFIX = (
    "ORGSET"
)